name: backend ci
on:
  push:
    paths-ignore:
      - 'frontend/**'
defaults:
  run:
    working-directory: ./backend
jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          working-directory: ./backend
          enable-cache: true
      - name: Run pre-commit hooks
        run: uv run --frozen pre-commit run --all-files
      - name: Run tests
        run: uv run --frozen pytest
        env:
          COLUMNS: 120
