name: ci
on:
  push:
jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hynek/setup-cached-uv@v2
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true
      - name: run prek (pre-commit)
        run: uvx prek --all-files
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: exiftool
          version: 1.0
      - uses: hynek/setup-cached-uv@v2
        with:
          cache-dependency-path: ./backend/pyproject.toml
      - name: Run tests
        run: uv run --frozen pytest
        env:
          COLUMNS: 120
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true
      - name: Run tests
        run: deno run test
