name: ci
on:
  push:
jobs:
  shared-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hynek/setup-cached-uv@v2
        with:
          cache-dependency-path: ./backend/pyproject.toml
      - uses: pre-commit/action@v3.0.1
  backend-ci:
    defaults:
      run:
        working-directory: ./backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hynek/setup-cached-uv@v2
        with:
          cache-dependency-path: ./backend/pyproject.toml
      - name: Run tests
        run: uv run --project ./backend --frozen pytest
        env:
          COLUMNS: 120
